# Generated by Django 3.1.2 on 2020-10-13 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mobile_number',
            new_name='mobileNumber',
        ),
    ]
