# Generated by Django 3.1.2 on 2020-10-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0003_auto_20201013_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='mobileNumber',
            field=models.CharField(max_length=18, null=True, unique=True),
        ),
    ]
